# No cycling between items upon repeated tab presses
setopt noautomenu

autoload -Uz colors && colors
autoload -Uz compinit && compinit
autoload edit-command-line; zle -N edit-command-line

RPROMPT="%2~"

# For vi mode specification
bindkey -v
bindkey -M vicmd v edit-command-line

# Enable reverse search
export HISTFILE=~/.zsh_history
export HISTSIZE=1000000
export SAVEHIST=1000000
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
bindkey '^R' history-incremental-search-backward # Seems to only work after vi mode settings


export KEYTIMEOUT=3  # lowers the lag time to switch to normal mode
COLORS=(red blue green cyan yellow magenta)
PROMPT_COLOR=$COLORS[$(( ${RANDOM} % 6 + 1))]
function zle-line-init zle-keymap-select {
    VIM_NORMAL_PROMPT="%{$fg_bold[yellow]%}[% N]% %{$reset_color%}:"
    VIM_INS_PROMPT="%{$fg_bold[green]%}[% I]% %{$reset_color%}:"
    PROMPT="%F{$PROMPT_COLOR}${SSH_CLIENT:+(%m)}%F{reset}${${KEYMAP/vicmd/$VIM_NORMAL_PROMPT}/(main|viins)/$VIM_INS_PROMPT}%D{%H%M%S}$ "
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
