- name: tmux | Install 'tmux'
  pacman:
    name: tmux
    state: present

- name: tmux | Set '.tmux.conf' file to user's home dir
  copy:
    src: tmux.conf
    dest: /home/peter/.tmux.conf
    owner: peter
    group: peter
